############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "https://sonaligroup.in/"
weight = 1

[[main]]
name = "Products"
url = "https://sonaligroup.in/sonali-products-main"
weight = 2


[[main]]
name = "Blog"
url = "/"
weight = 3


[[main]]
name = "Contact"
url = "contact/"
weight = 5






# footer menu
[[footer]]
name = "Home"
url = "https://sonaligroup.in/"
weight = 1

[[footer]]
name = "Products"
url = "https://sonaligroup.in/sonali-products-main"
weight = 2

[[footer]]
name = "Blog"
url = "/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "https://sonaligroup.in/privacy"
weight = 4

[[footer]]
name = "Terms & Conditions"
url = "https://sonaligroup.in/terms-and-conditions"
weight = 5
