############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "https://listingheroai.com"
weight = 1

[[main]]
name = "Blog"
url = "/"
weight = 2

[[main]]
name = "Login"
url = "https://app.listingheroai.com/login"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4






# footer menu
[[footer]]
name = "Home"
url = "https://listingheroai.com"
weight = 1

[[footer]]
name = "Blog"
url = "/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "https://listingheroai.com/privacy"
weight = 3

[[footer]]
name = "Terms & Conditions"
url = "https://listingheroai.com/terms"
weight = 4
