#################### default parameters ################################
favicon = "images/favicon.png"
logo = "images/logo.png"
logo_width = "175px"
logo_webp = true
logo_text = "ListingHero AI"

# footer information
footer_info = "Enhance Your Amazon Listings with AI"

# contact form action
contact_form_action = "https://formspree.io/f/your-sonali-form-id" 

custom_script= ""

# Main Sections
mainSections= [""]

# contact information
[contact_info]
address = "Golf Course Road, Gurgaon"
phone = ["+91-9001093913"]
email = ["info@listingheroai.com"]

# Preloader 
[preloader]
enable = false
preloader = "images/favicon.png"

# Navigation button
[navigation_button]
enable = true
label = "Try It Free"
link = "https://www.listingheroai.com"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["amazon", "ai", "image generator"]
description = "Listing Hero - Enhance Your Amazon Listings with AI"
author = "ListingHero"
image = "images/og-image.jpg"

# matomo tracking
[matomo]
enable = false
url = ""
id = ""

# baidu analytics
[baidu]
enable = false
analytics_id = ""

# plausible analytics
[plausible]
enable = false
domain = ""

# counter analytics
[counter]
enable = false
username = ""

# site verifications
[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""

# crisp chat
[crisp_chat]
enable = false
crisp_website_id = "your-crisp-id-if-used"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Enchance your Amazon listing in a few clicks!"
content = "With ability to generate content in a few clicks."
button = "Contact Us"
button_link = "/contact"

# buy premium popup
[buy_premium_popup]
enable = false
title = "Need help with Amazon listings?"
content = ""
button = "Contact Us"
button_link = "/contact"

# copyright
[copyright]
text = "© {year} ListingHero. All rights reserved."
