#################### default parameters ################################
favicon = "images/favicon.png"
logo = "images/logo.webp"
logo_width = "175px"
logo_webp = true
logo_text = "Sonali Polymers"

# footer information
footer_info = "Sonali Polymers is one of the fastest-growing manufacturers and exporters of fillers and masterbatches from India, delivering quality plastic solutions worldwide."

# contact form action
contact_form_action = "https://formspree.io/f/your-sonali-form-id" # Replace with actual Formspree ID

custom_script= ""

# Main Sections
mainSections= [""]

# contact information
[contact_info]
address = "Unit 807, 8th floor, Signature Elite Complex, Govind Marg, Narayan Singh circle , Jaipur, India"
phone = ["+91-9001093913"]
email = ["laura@mail.sonalipolymers.com"]

# Preloader 
[preloader]
enable = false
preloader = "images/favicon.png"

# Navigation button
[navigation_button]
enable = true
label = "Visit Website"
link = "https://www.sonaligroup.in"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Sonali Polymers", "Masterbatches", "Filler Manufacturer", "Plastic Compounds", "PVC", "Export from India"]
description = "Sonali Polymers is a leading manufacturer and exporter of fillers and masterbatches from India, with 60,000 MTA capacity and a strong global presence."
author = "Sonali Polymers"
image = "images/og-image.jpg"

# matomo tracking
[matomo]
enable = false
url = ""
id = ""

# baidu analytics
[baidu]
enable = false
analytics_id = ""

# plausible analytics
[plausible]
enable = false
domain = ""

# counter analytics
[counter]
enable = false
username = ""

# site verifications
[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""

# crisp chat
[crisp_chat]
enable = false
crisp_website_id = "your-crisp-id-if-used"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Global Innovators in Fillers and Masterbatches"
content = "With 60,000 MTA capacity and world-class manufacturing across India, Sonali delivers plastic solutions trusted around the globe."
button = "Contact Us"
button_link = "/contact"

# buy premium popup
[buy_premium_popup]
enable = false
title = "Need Custom Plastic Solutions?"
content = "Reach out to Sonali Polymers for specialized filler and masterbatch requirements tailored to your needs."
button = "Contact Us"
button_link = "/contact"

# copyright
[copyright]
text = "© {year} Sonali Polymers. All rights reserved."
